### ISSUE TITLE
Content Week Headers

### ISSUE THREAD

**Issue by amalnanavati** [v1shanker/TeknowledgeWebsite#7]
On the content page, can you center the header for each week (and possible make it larger than the individual lab titles)?  Right now it looks like "Week {#}: {Name}" is part of the first lab's title, and unrelated to the second lab (since it is directly on top of the first lab's title, that looks like the title and the lab name looks like a subtitle.)

**Comment by vikshanker** [comment]
I think the changes I made in the last couple of commits should address this. Feel free to reopen if you disagree.

**Comment by amalnanavati** [comment]
I like that you centered it, is there anyway you can increase the fontsize of the "Week _: ________" text?  Something like the fontsize of "Other Great Resources" or "A Computer Programming Curriculum..." would be great.  I tried naively changing it to h1 or h2 (I don't know much HTML/CSS) but that didn't work.

**Comment by vikshanker** [comment]
i think this fixed a while ago? feel free to reopen as always :P
